version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-26-alpha
    environment:
      JVM_OPTS: -Xmx2048m
      GRADLE_OPTS: -Xmx2048m -XX:+HeapDumpOnOutOfMemoryError -Dkotlin.compiler.execution.strategy=in-process -Dkotlin.incremental=false
    steps:
    - checkout
    - run:
        name: Add secrets.properties file
        command: touch ./secrets.properties
    - restore_cache:
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
    - run:
        name: Copy SDK License
        command: printf "8933bad161af4178b1185d1a37fbf41ea5269c55\nd56f5187479451eabf01fb78af6dfcb131a6481e\n24333f8a63b6825ea9c5514f83c2829b004d1fee\n" > ${ANDROID_HOME}/licenses/android-sdk-license
    - run:
        name: Download Dependencies
        command: ./gradlew androidDependencies
    - save_cache:
        paths:
        - ~/.gradle
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
    - run:
        name: Run Lint Tests
        command: ./gradlew lint test
    - run:
        name: Run Unit Tests
        command: ./gradlew :app:testApiMockDebugUnitTest
    - run:
        name: Show list of system-images
        command: sdkmanager --list --verbose | grep system-images
    - run:
        name: Setup Setup emulator
        command: |
          sdkmanager "system-images;android-21;default;armeabi-v7a"
          echo "no" | avdmanager create avd -n test -k "system-images;android-21;default;armeabi-v7a"
    - run:
        name: Launch emulator
        command: emulator -avd test -no-audio -no-window
        background: true
    - run:
        name: Wait emulator
        command: |
          circle-android wait-for-boot
          adb shell input keyevent 82
    - run:
        name: Run Instrumental Tests
        command: ./gradlew --no-daemon :app:connectedApiMockDebugAndroidTest
    - store_artifacts:
        path: app/build/reports
        destination: reports
    - store_test_results:
        path: app/build/test-results